apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./persistentVolumes/persistentvolume.yaml
  - ./persistentVolumes/persistentvolumeclaim.yaml
  - ./porsgresServices/HeadlessClusterIP.yml
  - ./porsgresServices/PostgresSecret.yml
  - ./porsgresServices/StatefullSetPorsgres.yml
  - ./manifest/ClusterIPService.yml
  - ./manifest/ClusterIPTodoService.yml
  - ./manifest/ConfigMap.yml
  - ./manifest/ConfigMapTodo.yml
  - ./manifest/CronJob.yml
  - ./manifest/Deployment.yml
  - ./manifest/DeploymentTodos.yml
  - ./manifest/IngressService.yml
images:
  - name: PROJECT/IMAGE_RANDOM-ARTICLE
    newName: zelhs/random-article
  - name: PROJECT/IMAGE_PROJECT_SERVER
    newName: zelhs/project_server
  - name: PROJECT/IMAGE_TODO_APP
    newName: zelhs/todoapp