name: Release application

on:
  push:
    branches:
      - main  

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-west1-b
  REGISTRY: europe-west1-docker.pkg.dev
  REPOSITORY: my-repository # Artifact registry for images
  BRANCH: ${{ github.ref_name }}

  # image names
  IMAGE_SERVER: zelhs/project_server
  IMAGE_TODO: zelhs/todoapp
  IMAGE_RANDOM: zelhs/random-article

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - run: gcloud --quiet auth configure-docker $REGISTRY

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      # Form image tags
      - name: 'Form image names'
        run: |
          echo "IMAGE_TAG_SERVER=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_SERVER:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV
          echo "IMAGE_TAG_TODO=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_TODO:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV
          echo "IMAGE_TAG_RANDOM=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_RANDOM:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      # Build & Push Server
      - name: Build & Push project_server
        run: |
          docker build -t $IMAGE_TAG_SERVER .
          docker push $IMAGE_TAG_SERVER

      # Build & Push todoApp
      - name: Build & Push todoApp
        run: |
          docker build -t $IMAGE_TAG_TODO ./todoApp
          docker push $IMAGE_TAG_TODO

      # Build & Push createRandomTodo
      - name: Build & Push createRandomTodo
        run: |
          docker build -t $IMAGE_TAG_RANDOM ./createRandomTodo
          docker push $IMAGE_TAG_RANDOM

      # Deploy
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Deploy
        run: |-
          kustomize edit set image PROJECT/IMAGE_SERVER=$IMAGE_TAG_SERVER
          kustomize edit set image PROJECT/IMAGE_TODO=$IMAGE_TAG_TODO
          kustomize edit set image PROJECT/IMAGE_RANDOM=$IMAGE_TAG_RANDOM
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment projectserver
          kubectl rollout status deployment todos-dep
          kubectl get cronjob random-article-job
