apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-image-pv 
spec:
  storageClassName: shared-image-pv 
  capacity:
    storage: 1Gi 
  volumeMode: Filesystem 
  accessModes:
  - ReadWriteOnce
  local:
    path: /tmp/kube/imageCache
  nodeAffinity: 
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-k3s-default-agent-0