apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project
  name: shared-image-pv-claim 
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi