apiVersion: v1
kind: Secret
metadata:
  namespace: project
  name: postgres-secret
type: Opaque
stringData: 
  POSTGRES_USER: "myuser"
  POSTGRES_PASSWORD: "mypassword"
  POSTGRES_DB: "mydb"
  POSTGRES_HOST: "postgres-svc.project.svc.cluster.local"
  POSTGRES_PORT: "5432"
