apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: project
  name: random-article-job
spec:
  schedule: "0 * * * *"  # every hour at minute 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: random-article
            image: PROJECT/IMAGE_RANDOM
            resources:
              requests:
                cpu: "50m"
                memory: "64Mi"
              limits:
                cpu: "200m"
                memory: "128Mi"
          restartPolicy: Never
