apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: project
  name: random-article-job
spec:
  schedule: "0 * * * *"  # every hour at minute 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: random-article
            image: PROJECT/IMAGE_RANDOM_ARTICLE
          restartPolicy: Never
