apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: projectserver-dep
spec:
  replicas: 1
  selector:
      matchLabels:
        app: projectserver
  template:
      metadata:
        labels:
            app: projectserver
      spec:
        volumes: 
        - name: shared-image
          persistentVolumeClaim:
            claimName: shared-image-pv-claim
        containers:
        - name: projectserver
          image: zelhs/project_server:2.2
          volumeMounts: 
          - name: shared-image
            mountPath: '/usr/app/public/image'