apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: projectserver-dep
spec:
  replicas: 1
  selector:
      matchLabels:
        app: projectserver
  template:
      metadata:
        labels:
            app: projectserver
      spec:
        volumes: 
        - name: shared-image
          persistentVolumeClaim:
            claimName: shared-image-pv-claim
        containers:
        - name: projectserver
          image: PROJECT/IMAGE_PROJECT_SERVER
          envFrom:
            - configMapRef:
                name: projectserver-config
          volumeMounts: 
          - name: shared-image
            mountPath: '/usr/app/public/image'
            subPath: image
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"