apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: projectserver-dep
spec:
  replicas: 1
  selector:
      matchLabels:
        app: projectserver
  template:
      metadata:
        labels:
            app: projectserver
      spec:
        volumes: 
          - name: shared-image
            persistentVolumeClaim:
              claimName: shared-image-pv-claim
          - name: public-files
            emptyDir: {}
        initContainers:
          - name: copy-public
            image: PROJECT/IMAGE_PROJECT_SERVER
            command: ['sh', '-c', 'cp -r /usr/app/public/* /shared-public/ 2>/dev/null || echo "Copying public files"; mkdir -p /shared-public/image']
            volumeMounts:
            - name: public-files
              mountPath: /shared-public
        containers:
        - name: projectserver
          image: PROJECT/IMAGE_PROJECT_SERVER
          envFrom:
            - configMapRef:
                name: projectserver-config
          volumeMounts: 
          - name: shared-image
            mountPath: '/usr/app/public/image'
          - name: public-files
            mountPath: '/usr/app/public'       
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"