apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-server-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/andreasZel/devops_with_kubernetes_project_server.git
    targetRevision: HEAD
    path: project_server/manifest/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true