apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster-dep
spec:
  template:
    spec:
      containers:
      - name: broadcaster
        env:
        - name: LOG_ONLY
          value: "true"
        - name: DISCORD_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: broadcaster-secret
              key: DISCORD_WEBHOOK_URL
              optional: true